# Generated by Django 2.0.1 on 2018-03-15 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('empresa', models.CharField(max_length=100)),
                ('nit', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cod_verificacion', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresasUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Empresas')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='plataforma', max_length=15)),
                ('version', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TypeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('C', 'Cliente'), ('S', 'Soporte'), ('T', 'Teconologia'), ('A', 'Administrador')], max_length=1)),
                ('is_chief', models.BooleanField(default=False)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='empresas',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Plataforma'),
        ),
    ]
