# Generated by Django 2.0.1 on 2018-03-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plataforma',
            new_name='Plataformas',
        ),
    ]
