# Generated by Django 2.0.1 on 2018-03-21 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0002_auto_20180320_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'Cliente'), ('S', 'Soporte'), ('T', 'Teconologia'), ('A', 'Administrador')], max_length=1)),
                ('is_chief', models.BooleanField(default=False)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='typeuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='empresas',
            name='telefono',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TypeUser',
        ),
    ]
