# Generated by Django 2.0.1 on 2018-07-03 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20180625_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentes',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentes',
            name='prioridad_respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='administracion.PrioridadesRespuesta'),
        ),
        migrations.AlterField(
            model_name='incidentes',
            name='tipo_incidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='administracion.TiposIncidentes'),
        ),
    ]
