# Generated by Django 2.0.1 on 2018-07-04 11:56

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20180704_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjuntos',
            name='archivo',
            field=models.FileField(upload_to=usuarios.models.my_awesome_upload_function),
        ),
    ]
