# Generated by Django 2.0.1 on 2018-07-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20180705_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientosestadosincidentes',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='movimientosestadosincidentes',
            name='incidente',
        ),
        migrations.RemoveField(
            model_name='movimientosestadosincidentes',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='MovimientosEstadosIncidentes',
        ),
    ]
