# Generated by Django 2.0.1 on 2018-07-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_auto_20180705_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentes',
            name='titulo',
            field=models.CharField(default='titulo', max_length=50),
            preserve_default=False,
        ),
    ]
