# Generated by Django 2.0.1 on 2018-07-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_incidentes_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentes',
            name='titulo',
            field=models.CharField(max_length=80),
        ),
    ]
