# Generated by Django 2.0.1 on 2018-07-26 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_auto_20180711_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariossoporteincidentes',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_soporte', to=settings.AUTH_USER_MODEL),
        ),
    ]
