# Generated by Django 2.0.1 on 2018-07-27 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_auto_20180726_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosincidentes',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_incidentes', to=settings.AUTH_USER_MODEL),
        ),
    ]
