# Generated by Django 2.0.1 on 2018-07-27 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_auto_20180727_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjuntos',
            name='incidente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='usuarios.Incidentes'),
        ),
        migrations.AlterField(
            model_name='usuariossoporteincidentes',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes_soporte', to=settings.AUTH_USER_MODEL),
        ),
    ]
