# Generated by Django 2.0.1 on 2018-07-27 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_auto_20180727_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentes',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to=settings.AUTH_USER_MODEL),
        ),
    ]
