# Generated by Django 2.0.1 on 2018-07-30 11:52

import django.core.files.storage
from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_auto_20180727_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjuntos',
            name='incidente',
        ),
        migrations.AddField(
            model_name='adjuntos',
            name='nombre_archivo',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='adjuntos',
            name='archivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/mnt/c/Users/arju/Desktop/Grexco/Proyectos/Web/grexco/usuarios/'), upload_to=usuarios.models.my_awesome_upload_function),
        ),
    ]
