# Generated by Django 2.0.1 on 2018-07-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_auto_20180730_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjuntos',
            name='nombre_archivo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
