# ========================================
# Para crear las aplicaciones masivamente
# ========================================

from administracion.models import Aplicaciones

apl = [
    "ActivosFijos",
    "AdminPventa",
    "Bancos",
    "Bolos",
    "CajaMenor",
    "Compras",
    "Contratistas",
    "CuentasCobro",
    "FichaTecnica",
    "GrexAcfiPDA",
    "GrexCntl",
    "GrexCont",
    "GrexRegi",
    "GXAcfi",
    "GXBackUp",
    "GXBanc",
    "GXCaja",
    "GXComp",
    "GXCont",
    "GXDota",
    "GXDotaSetup",
    "GXHelpDesk",
    "GxInic",
    "GXInve",
    "GXInvePDA",
    "GXNomi",
    "GXOpeMin",
    "GXProd",
    "GXRegi",
    "GXRestA",
    "GXRestC",
    "GXRestF",
    "GXRestT",
    "GXRestTA",
    "GXSegu",
    "GXSetup",
    "GXSetup64",
    "GXTerc",
    "GXTeso",
    "GXVent",
    "Inicio",
    "Inventarios",
    "NFAcfi",
    "NFBanc",
    "NFCaja",
    "NFComp",
    "NFCont",
    "NFInic",
    "NFInve",
    "NFNomi",
    "NFProd",
    "NFRegistroPP",
    "NFSegu",
    "NFTerc",
    "NFTeso",
    "NFVent",
    "Nomina",
    "PERSONAS",
    "Produccion",
    "PuntoVenta",
    "PuntoVentaBolos",
    "Seguridad",
    "TesoCntl",
    "Tesoreria",
    "Ventas",
]

for a in apl:
    app = Aplicaciones()
    app.nombre = a
    print(app.nombre)
    app.save()
