# Generated by Django 2.0.1 on 2018-05-29 14:15

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tecnologia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosPruebas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/grexco'), upload_to='pruebas/<django.db.models.fields.related.ForeignKey>')),
            ],
        ),
        migrations.CreateModel(
            name='Pruebas',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cambio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruebas', to='tecnologia.Cambios')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadosPruebas',
            fields=[
                ('codigo', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pruebas',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruebas', to='soporte.ResultadosPruebas'),
        ),
        migrations.AddField(
            model_name='archivospruebas',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos', to='soporte.Pruebas'),
        ),
    ]
