# Generated by Django 2.0.1 on 2018-07-24 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_auto_20180711_1252'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasSoporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.Incidentes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_soporte', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotasTecnologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.Incidentes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_tecnologia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
