# Generated by Django 2.0.1 on 2018-04-17 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Convenios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.Aplicaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('nit', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='HorariosSoporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('descripcion', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('MI', 'Miercoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sabado'), ('D', 'Domingo')], max_length=2)),
                ('inicio', models.IntegerField(null=True)),
                ('fin', models.IntegerField(null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.Empresas')),
            ],
        ),
        migrations.CreateModel(
            name='Plataformas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PrioridadesRespuesta',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.Aplicaciones')),
            ],
        ),
        migrations.CreateModel(
            name='TiemposRespuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_horas', models.IntegerField(null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.Empresas')),
                ('prioridades_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.PrioridadesRespuesta')),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosGrexco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'Cliente'), ('S', 'Soporte'), ('T', 'Teconologia'), ('A', 'Administrador')], max_length=1)),
                ('es_coordinador', models.BooleanField(default=False)),
                ('telefono', models.CharField(default=0, max_length=15)),
                ('extension', models.IntegerField(default=0)),
                ('cargo', models.CharField(max_length=30)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.Empresas')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='empresas',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.Plataformas'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.Empresas'),
        ),
    ]
