# Generated by Django 2.0.1 on 2018-03-27 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Convenios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicaciones_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Aplicaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('nit', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Plataformas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PrioridadesRespuesta',
            fields=[
                ('codigo', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('aplicaciones_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Aplicaciones')),
            ],
        ),
        migrations.CreateModel(
            name='TiemposRespuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_horas', models.IntegerField()),
                ('prioridades_respuesta_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.PrioridadesRespuesta')),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosGrexco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'Cliente'), ('S', 'Soporte'), ('T', 'Teconologia'), ('A', 'Administrador')], max_length=1)),
                ('es_coordinador', models.BooleanField(default=False)),
                ('telefono', models.CharField(default=0, max_length=15)),
                ('extension', models.IntegerField(default=0)),
                ('empresas_nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Empresas')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='empresas',
            name='plataformas_nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Plataformas'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='empresas_nit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Empresas'),
        ),
    ]
