# Generated by Django 2.0.1 on 2018-04-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataformas',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
