# Generated by Django 2.0.1 on 2018-05-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiemposrespuesta',
            old_name='prioridades_respuesta',
            new_name='prioridad',
        ),
        migrations.RemoveField(
            model_name='tiemposrespuesta',
            name='tiempo_horas',
        ),
        migrations.AddField(
            model_name='tiemposrespuesta',
            name='tiempo',
            field=models.TimeField(null=True),
        ),
    ]
