# Generated by Django 2.0.1 on 2018-04-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prioridadesrespuesta',
            name='codigo',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
