# Generated by Django 2.0.1 on 2018-04-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicaciones',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
