# Generated by Django 2.0.1 on 2018-05-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20180530_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiemposrespuesta',
            name='tiempo',
            field=models.IntegerField(default=3),
        ),
    ]
