# Generated by Django 2.0.1 on 2018-04-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20180417_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicaciones',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
