# Generated by Django 2.0.1 on 2018-04-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20180406_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosgrexco',
            name='cargo',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
