# Generated by Django 2.0.1 on 2018-06-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_empresas_activa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenios',
            name='aplicacion',
        ),
        migrations.AddField(
            model_name='convenios',
            name='aplicacion',
            field=models.ManyToManyField(to='administracion.Aplicaciones'),
        ),
        migrations.RemoveField(
            model_name='convenios',
            name='empresa',
        ),
        migrations.AddField(
            model_name='convenios',
            name='empresa',
            field=models.ManyToManyField(to='administracion.Empresas'),
        ),
    ]
