# Generated by Django 2.0.1 on 2018-06-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_auto_20180607_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenios',
            name='aplicacion',
        ),
        migrations.AddField(
            model_name='convenios',
            name='aplicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='administracion.Aplicaciones'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='convenios',
            name='empresa',
        ),
        migrations.AddField(
            model_name='convenios',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='convenios', to='administracion.Empresas'),
            preserve_default=False,
        ),
    ]
