# Generated by Django 2.0.1 on 2018-06-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_auto_20180608_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convenios',
            old_name='aplicacion',
            new_name='aplicacion_id',
        ),
        migrations.RenameField(
            model_name='convenios',
            old_name='empresa',
            new_name='empresa_nit',
        ),
    ]
