# Generated by Django 2.0.1 on 2018-06-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_auto_20180608_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convenios',
            old_name='aplicacion_id',
            new_name='aplicacion',
        ),
        migrations.RenameField(
            model_name='convenios',
            old_name='empresa_nit',
            new_name='empresa',
        ),
    ]
