# Generated by Django 2.0.1 on 2018-06-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_auto_20180608_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenios',
            name='aplicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convenios', to='administracion.Aplicaciones'),
        ),
    ]
