# Generated by Django 2.0.1 on 2018-06-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_auto_20180613_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposIncidentes',
            fields=[
                ('codigo', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
    ]
