# Generated by Django 2.0.1 on 2018-02-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
