# Generated by Django 2.0.1 on 2018-04-25 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0004_auto_20180423_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionesAplicaciones',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20)),
                ('commit', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones', to='administracion.Aplicaciones')),
            ],
        ),
    ]
